[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open-wam"
version = "0.1.0"
description = "OpenWAM: A Modular Open-Source Library for Systematic WAM Training, Inference and Deployment"
authors = [{name = "OpenWAM Contributors"}]
license = {text = "MIT"}
requires-python = ">=3.10.1"
dependencies = [
    "numpy<3",
    "Pillow<12",
    "torch>=2.0.0,<3",
    "torchvision<1",
    "transformers<5",
    "imageio<3",
    "imageio[ffmpeg]<3",
    "safetensors<1",
    "einops<1",
    "sentencepiece<1",
    "protobuf<6",
    "modelscope<2",
    "ftfy<7",
    "h5py<4",
    "lpips<1",
    "pandas<3",
    "scikit-image<1",
    "accelerate<2",
    "peft<1",
    "datasets<4",
    "tqdm<5",
    "wandb<1",
    "hydra-core>=1.3,<2",
    "omegaconf>=2.3,<3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["./"]
include = ["open_wam", "open_wam.*", "third_party.diffsynth", "third_party.diffsynth.*"]

[project.optional-dependencies]
serving = [
    "websockets<15",
    "aiohttp<4"
]
npu_aarch64 = [
    "torch==2.7.1",
    "torch-npu==2.7.1",
    "torchvision==0.22.1"
]
npu = [
    "torch==2.7.1+cpu",
    "torch-npu==2.7.1",
    "torchvision==0.22.1+cpu"
]

[tool.setuptools]
include-package-data = true

[project.scripts]
openwam-serve = "open_wam.serving.policy_server:main"
