[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open-wam"
version = "0.1.0"
description = "OpenWAM: A Modular Open-Source Library for Systematic WAM Training, Inference and Deployment"
authors = [{name = "OpenWAM Contributors"}]
license = {text = "MIT"}
requires-python = ">=3.10.1"
dependencies = [
    "numpy",
    "Pillow",
    "torch>=2.0.0",
    "torchvision",
    "transformers",
    "imageio",
    "imageio[ffmpeg]",
    "safetensors",
    "einops",
    "sentencepiece",
    "protobuf",
    "modelscope",
    "ftfy",
    "h5py",
    "lpips",
    "pandas",
    "scikit-image",
    "accelerate",
    "peft",
    "datasets",
    "tqdm",
    "wandb",
    "hydra-core>=1.3",
    "omegaconf>=2.3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["./"]
include = ["open_wam", "open_wam.*", "third_party.diffsynth", "third_party.diffsynth.*"]

[project.optional-dependencies]
serving = [
    "websockets",
    "aiohttp"
]
npu_aarch64 = [
    "torch==2.7.1",
    "torch-npu==2.7.1",
    "torchvision==0.22.1"
]
npu = [
    "torch==2.7.1+cpu",
    "torch-npu==2.7.1",
    "torchvision==0.22.1+cpu"
]

[tool.setuptools]
include-package-data = true

[project.scripts]
openwam-serve = "open_wam.serving.policy_server:main"
