type: robocoin

dataset_dir: /path/to/RoboCOIN

num_frames: 33
video_stride: 4
window_stride: 1

height: 384
width: 320

multiview: true

split: train

normalize_mode: quantile

enable_action_supervision: true

unify_action: false
unify_action_map: ["0-9", "32-41"]

total_hours: null
