lambda_video: 0.0
lambda_action: 1.0
learning_rate: 1e-4
action_lr: 5e-5
video_lr: null
lora_lr: null
weight_decay: 0.01
num_epochs: 1
max_steps: null
batch_size: 1
gradient_accumulation_steps: 4
use_gradient_checkpointing: false
use_gradient_checkpointing_offload: false
max_timestep_boundary: 1.0
min_timestep_boundary: 0.0
find_unused_parameters: false

model_paths: null
model_id_with_origin_paths: null
tokenizer_path: null
trainable_models: []
initialize_model_on_cpu: false

lora_base_model: null
lora_target_modules: "q,k,v,o,ffn.0,ffn.2"
lora_rank: 32
lora_checkpoint: null
preset_lora_path: null
preset_lora_model: null

fp8_models: null
offload_models: null

output_path: ./models
remove_prefix_in_ckpt: "pipe.dit."
save_steps: null
rolling_save_steps: null
keep_last_k_ckpts: 2
dataset_num_workers: 0

val_steps: null
video_log_steps: null
