"""Public implementation. Dataset-specific audit notes were removed."""















































from __future__ import annotations

import argparse
import json
import logging
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from openwam.dataloader.oxe_droid import (
    DROID_PROMPT_EXCLUSION_KEY,
    DROID_PROMPT_EXCLUSION_SCHEMA_VERSION,
    DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY,
    OxeDroidDataset,
    _clean_text,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

FALLBACK_COLS = list(OxeDroidDataset.PROMPT_FALLBACK_COLS)
PROMPT_REASON = (
    "episodes whose prompt cannot be resolved from tasks.parquet or any "
    "PROMPT_FALLBACK_COLS entry on any row; generated by "
    "scripts/write_droid_prompt_exclusions.py"
)
_TASK_TEXT: dict[int, str] | None = None
_DATASET_DIR: Path | None = None


def _init(dataset_dir: str) -> None:
    global _TASK_TEXT, _DATASET_DIR
    _DATASET_DIR = Path(dataset_dir)
    tasks = pd.read_parquet(_DATASET_DIR / "meta" / "tasks.parquet")
    _TASK_TEXT = dict(zip(tasks["task_index"].to_numpy().tolist(), tasks.index.to_numpy().tolist()))


def _scan_shard(rel_path: str) -> dict:
    """Public implementation. Dataset-specific audit notes were removed."""
    assert _TASK_TEXT is not None and _DATASET_DIR is not None
    path = _DATASET_DIR / rel_path
    cols = ["episode_index", "task_index", *FALLBACK_COLS]
    df = pq.read_table(path, columns=cols, memory_map=True).to_pandas()
    n = len(df)
    task_idx = df["task_index"].to_numpy()


    cleaned_by_task = {int(t): _clean_text(_TASK_TEXT.get(int(t))) for t in np.unique(task_idx)}
    missing = sorted(t for t in cleaned_by_task if t not in _TASK_TEXT)
    resolved = np.array([cleaned_by_task[int(t)] for t in task_idx], dtype=object)



    for col in FALLBACK_COLS:
        todo = resolved == ""
        if not todo.any():
            break
        codes, uniques = pd.factorize(df[col], use_na_sentinel=False)
        cleaned = np.array([_clean_text(u) for u in uniques], dtype=object)[codes]
        hit = todo & (cleaned != "")
        resolved[hit] = cleaned[hit]

    unresolved = pd.Series(resolved == "")
    by_ep = unresolved.groupby(df["episode_index"].to_numpy())
    all_bad = by_ep.all()
    any_bad = by_ep.any()
    return {
        "rows": n,
        "unresolved_rows": int(unresolved.sum()),
        "episodes_all_unresolved": [int(i) for i in all_bad[all_bad].index.tolist()],



        "episodes_partially_unresolved": [int(i) for i in any_bad[any_bad & ~all_bad].index.tolist()],
        "task_index_missing_from_tasks_parquet": missing,
    }


def _parse_episode_indices(value, field: str) -> set[int]:
    if not isinstance(value, list) or any(type(i) is not int or i < 0 for i in value):
        raise ValueError(f"{field} must be a list of non-negative integers")
    return set(value)


def _atomic_write_text(path: Path, text: str, expected: bytes | None) -> None:
    """Public implementation. Dataset-specific audit notes were removed."""
    tmp = path.with_suffix(path.suffix + f".{os.getpid()}.tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        current = path.read_bytes() if path.exists() else None
        if current != expected:
            raise SystemExit(f"{path} changed during the prompt scan; refusing to overwrite newer exclusions")
        tmp.replace(path)
    finally:
        tmp.unlink(missing_ok=True)


def _is_original_generator_artifact(previous: dict, existing: set[int]) -> bool:
    """Public implementation. Dataset-specific audit notes were removed."""
    if set(previous) != {"reason", "generated", "episode_indices", "stats"}:
        return False
    if previous["reason"] != PROMPT_REASON or not isinstance(previous["generated"], str):
        return False
    if previous["episode_indices"] != sorted(existing):
        return False
    stats = previous["stats"]
    if not isinstance(stats, dict) or set(stats) != {
        "rows_scanned",
        "unresolved_rows",
        "episodes_all_unresolved",
        "episodes_partially_unresolved",
        "fallback_chain",
    }:
        return False
    int_fields = (
        "rows_scanned",
        "unresolved_rows",
        "episodes_all_unresolved",
        "episodes_partially_unresolved",
    )
    if any(type(stats[field]) is not int or stats[field] < 0 for field in int_fields):
        return False
    return (
        stats["rows_scanned"] > 0
        and stats["unresolved_rows"] <= stats["rows_scanned"]
        and stats["episodes_all_unresolved"] == len(existing)
        and stats["episodes_partially_unresolved"] == 0
        and stats["fallback_chain"] == FALLBACK_COLS
    )


def _load_existing_ownership(out: Path) -> tuple[dict, dict, set[int], bytes | None]:
    """Public implementation. Dataset-specific audit notes were removed."""
    if not out.exists():
        return {}, {}, set(), None
    try:
        snapshot = out.read_bytes()
        previous = json.loads(snapshot)
        if not isinstance(previous, dict):
            raise ValueError("top-level value must be an object")
        existing = _parse_episode_indices(previous["episode_indices"], "episode_indices")
        if DROID_PROMPT_EXCLUSION_KEY in previous:
            previous_prompt = previous[DROID_PROMPT_EXCLUSION_KEY]
            if not isinstance(previous_prompt, dict):
                raise ValueError(f"{DROID_PROMPT_EXCLUSION_KEY} must be an object")
            prompt_owned = _parse_episode_indices(
                previous_prompt["episode_indices"],
                f"{DROID_PROMPT_EXCLUSION_KEY}.episode_indices",
            )
            try:
                independently_owned = _parse_episode_indices(
                    previous_prompt[DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY],
                    f"{DROID_PROMPT_EXCLUSION_KEY}.{DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY}",
                )
            except KeyError as exc:
                raise ValueError(
                    f"{DROID_PROMPT_EXCLUSION_KEY} has no independent ownership ledger; refusing an unsafe rescan"
                ) from exc
            if existing != prompt_owned | independently_owned:
                raise ValueError(
                    "episode_indices must equal the union of prompt-owned and independently-owned exclusions"
                )
            return previous, previous_prompt, independently_owned, snapshot
        if _is_original_generator_artifact(previous, existing):



            return {}, {}, set(), snapshot


        return previous, {}, existing, snapshot
    except (KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"existing exclusion file {out} is malformed ({exc}); refusing to replace it") from exc


def _validate_total_frames(root: Path, rows_scanned: int) -> None:
    """Public implementation. Dataset-specific audit notes were removed."""
    info_path = root / "meta" / "info.json"
    if not info_path.exists():
        return
    try:
        info = json.loads(info_path.read_text())
        if not isinstance(info, dict):
            raise ValueError("top-level value must be an object")
        if "total_frames" not in info:
            return
        expected = info["total_frames"]
        if type(expected) is not int or expected < 0:
            raise ValueError("total_frames must be a non-negative integer")
    except (TypeError, ValueError) as exc:
        raise SystemExit(f"{info_path} is malformed ({exc}); refusing to publish exclusions") from exc
    if rows_scanned != expected:
        raise SystemExit(
            f"prompt scan covered {rows_scanned} rows but {info_path} declares total_frames={expected}; "
            "refusing to publish exclusions"
        )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset-dir", required=True, help="DROID LeRobot v3 bucket root")
    ap.add_argument("--workers", type=int, default=min(32, (os.cpu_count() or 8)))
    ap.add_argument("--dry-run", action="store_true", help="Print the verdict, write nothing")
    args = ap.parse_args()

    root = Path(args.dataset_dir)
    out = root / "meta" / "excluded_episodes.json"
    previous, previous_prompt, independently_owned, existing_snapshot = _load_existing_ownership(out)
    shards = sorted(p.relative_to(root).as_posix() for p in (root / "data").rglob("*.parquet"))
    if not shards:
        raise FileNotFoundError(f"no data parquet under {root}/data")
    logger.info("scanning %d shards under %s with %d workers", len(shards), root, args.workers)

    results = []
    with ProcessPoolExecutor(max_workers=args.workers, initializer=_init, initargs=(str(root),)) as ex:
        futs = [ex.submit(_scan_shard, s) for s in shards]
        for i, f in enumerate(as_completed(futs), 1):
            results.append(f.result())
            if i % 50 == 0 or i == len(shards):
                logger.info("  %d/%d shards", i, len(shards))

    bad = sorted({e for r in results for e in r["episodes_all_unresolved"]})
    partial = sorted({e for r in results for e in r["episodes_partially_unresolved"]})
    missing = sorted({t for r in results for t in r["task_index_missing_from_tasks_parquet"]})
    rows = sum(r["rows"] for r in results)
    bad_rows = sum(r["unresolved_rows"] for r in results)

    logger.info("rows scanned: %d", rows)
    logger.info("unresolved rows: %d (%.3f%%)", bad_rows, bad_rows / max(rows, 1) * 100)
    logger.info("episodes with NO resolvable prompt on any row: %d", len(bad))
    if partial:
        logger.error(
            "%d episodes are only PARTIALLY unresolvable — the all-or-nothing assumption this "
            "exclusion list relies on does not hold for them: %s",
            len(partial),
            partial[:20],
        )
    if missing:
        logger.error("task_index values absent from tasks.parquet: %s", missing[:20])
    if partial or missing:
        raise SystemExit(
            "prompt scan violated reader invariants; refusing to publish an exclusion file "
            f"(partially unresolved episodes={len(partial)}, missing task_index values={len(missing)})"
        )
    _validate_total_frames(root, rows)

    stats = {
        "rows_scanned": rows,
        "unresolved_rows": bad_rows,
        "episodes_all_unresolved": len(bad),
        "episodes_partially_unresolved": len(partial),
        "task_index_missing_from_tasks_parquet": len(missing),
        "fallback_chain": FALLBACK_COLS,
    }
    merged = sorted(independently_owned | set(bad))
    prompt_payload = {
        **previous_prompt,
        "reason": PROMPT_REASON,
        "schema_version": DROID_PROMPT_EXCLUSION_SCHEMA_VERSION,
        "fallback_chain": FALLBACK_COLS,
        "episode_indices": bad,
        DROID_PROMPT_INDEPENDENT_EXCLUSIONS_KEY: sorted(independently_owned),
        "latest_scan": {
            "generated": date.today().isoformat(),
            "episode_indices": bad,
            "stats": stats,
        },
    }
    payload = {
        **previous,
        "episode_indices": merged,
        DROID_PROMPT_EXCLUSION_KEY: prompt_payload,
    }
    if args.dry_run:
        logger.info(
            "--dry-run: would merge %d prompt exclusions into %s (%d total episode_indices)",
            len(bad),
            out,
            len(merged),
        )
        return
    _atomic_write_text(out, json.dumps(payload, indent=2) + "\n", expected=existing_snapshot)
    logger.info(
        "wrote %s (%d prompt exclusions, %d existing exclusions preserved, %d total)",
        out,
        len(bad),
        len(independently_owned),
        len(merged),
    )


if __name__ == "__main__":
    main()
