flux_general_vram_config = {
    "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "torch.nn.GroupNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "openwam.model.video_backbone.diffsynth.models.general_modules.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "openwam.model.video_backbone.diffsynth.models.flux_lora_encoder.LoRALayerBlock": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    "openwam.model.video_backbone.diffsynth.models.flux_lora_patcher.LoraMerger": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
}

VRAM_MANAGEMENT_MODULE_MAPS = {
    "openwam.model.video_backbone.diffsynth.models.qwen_image_dit.QwenImageDiT": {
        "openwam.model.video_backbone.diffsynth.models.qwen_image_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.qwen_image_text_encoder.QwenImageTextEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLRotaryEmbedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VisionPatchEmbed": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VisionRotaryEmbedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.qwen_image_vae.QwenImageVAE": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.qwen_image_vae.QwenImageRMS_norm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.qwen_image_controlnet.BlockWiseControlBlock": {
        "openwam.model.video_backbone.diffsynth.models.qwen_image_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.siglip2_image_encoder.Siglip2ImageEncoder": {
        "transformers.models.siglip.modeling_siglip.SiglipVisionEmbeddings": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipMultiheadAttentionPoolingHead": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.dinov3_image_encoder.DINOv3ImageEncoder": {
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTLayerScale": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTRopePositionEmbedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTEmbeddings": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.qwen_image_image2lora.QwenImageImage2LoRAModel": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.WanAnimateAdapter": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.FaceEncoder": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.EqualLinear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.ConvLayer": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.FusedLeakyReLU": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_animate_adapter.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv1d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_dit_s2v.WanS2VModel": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.Head": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit_s2v.WanS2VDiTBlock": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit_s2v.CausalAudioEncoder": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_dit.WanModel": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.MLP": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.DiTBlock": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedNonRecurseModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.Head": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_image_encoder.WanImageEncoder": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_image_encoder.VisionTransformer": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_mot.MotWanModel": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_mot.MotWanAttentionBlock": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_motion_controller.WanMotionControllerModel": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_text_encoder.WanTextEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_text_encoder.T5RelativeEmbedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_text_encoder.T5LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_vace.VaceWanModel": {
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.DiTBlock": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_vae.WanVideoVAE": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.RMS_norm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.CausalConv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.Upsample": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.SiLU": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Dropout": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wan_video_vae.WanVideoVAE38": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.RMS_norm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.CausalConv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.wan_video_vae.Upsample": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.SiLU": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Dropout": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.wav2vec.WanS2VAudioEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv1d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.longcat_video_dit.LongCatVideoTransformer3DModel": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.longcat_video_dit.RMSNorm_FP32": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.longcat_video_dit.LayerNorm_FP32": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux_dit.FluxDiT": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "openwam.model.video_backbone.diffsynth.models.flux_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux_text_encoder_clip.FluxTextEncoderClip": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_vae.FluxVAEEncoder": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_vae.FluxVAEDecoder": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_controlnet.FluxControlNet": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_infiniteyou.InfiniteYouImageProjector": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_ipadapter.FluxIpAdapter": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_lora_patcher.FluxLoraPatcher": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.step1x_connector.Qwen2Connector": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_lora_encoder.FluxLoRAEncoder": flux_general_vram_config,
    "openwam.model.video_backbone.diffsynth.models.flux_text_encoder_t5.FluxTextEncoderT5": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5DenseActDense": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5DenseGatedActDense": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux_ipadapter.SiglipVisionModelSO400M": {
        "transformers.models.siglip.modeling_siglip.SiglipVisionEmbeddings": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipEncoder": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipMultiheadAttentionPoolingHead": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.MultiheadAttention": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux2_dit.Flux2DiT": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux2_text_encoder.Flux2TextEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.mistral.modeling_mistral.MistralRMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.flux2_vae.Flux2VAE": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.GroupNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.z_image_text_encoder.ZImageTextEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "transformers.models.qwen3.modeling_qwen3.Qwen3RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.z_image_dit.ZImageDiT": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "openwam.model.video_backbone.diffsynth.models.z_image_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.z_image_controlnet.ZImageControlNet": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "openwam.model.video_backbone.diffsynth.models.z_image_dit.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.z_image_image2lora.ZImageImage2LoRAModel": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.siglip2_image_encoder.Siglip2ImageEncoder428M": {
        "transformers.models.siglip2.modeling_siglip2.Siglip2VisionEmbeddings": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip2.modeling_siglip2.Siglip2MultiheadAttentionPoolingHead": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_dit.LTXModel": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_upsampler.LTX2LatentUpsampler": {
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.GroupNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_video_vae.LTX2VideoEncoder": {
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_video_vae.LTX2VideoDecoder": {
        "torch.nn.Conv3d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_audio_vae.LTX2AudioDecoder": {
        "torch.nn.Conv2d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_audio_vae.LTX2Vocoder": {
        "torch.nn.Conv1d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "torch.nn.ConvTranspose1d": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_text_encoder.LTX2TextEncoderPostModules": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "torch.nn.RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "openwam.model.video_backbone.diffsynth.models.ltx2_text_encoder.Embeddings1DConnector": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
    "openwam.model.video_backbone.diffsynth.models.ltx2_text_encoder.LTX2TextEncoder": {
        "torch.nn.Linear": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedLinear",
        "transformers.models.gemma3.modeling_gemma3.Gemma3MultiModalProjector": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.gemma3.modeling_gemma3.Gemma3RMSNorm": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
        "transformers.models.gemma3.modeling_gemma3.Gemma3TextScaledWordEmbedding": "openwam.model.video_backbone.diffsynth.core.vram.layers.AutoWrappedModule",
    },
}
